name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - 'renovate/**'
    tags:
      - 'v*'
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}

      - run: yarn
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: yarn lint

      - run: yarn build

      - name: Preview
        if: ${{ (matrix.node-version == '14') && (github.ref == 'refs/heads/master') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: deploy ${{ github.ref }}
          force_orphan: true
          publish_branch: preview

  dist:
    runs-on: ubuntu-latest
    needs: main
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-14-${{ hashFiles('yarn.lock') }}

      - run: yarn
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: yarn build

      - run: |
          sudo apt-get install tree -y
          tree -H '.' -L 1 --noreport --charset utf-8 ./dist | tee dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: deploy ${{ github.ref }}
